const kamus = {
    id: {
        'judul_1': 'PEKAN PERKENALAN',
        'judul_2': "KHUTBATU-L-'ARSY",
        'slogan': '"Pesantren melahirkan santri yang tangguh, menciptakan peradaban yang utuh."',
        'narasi_pembuka': "Ditengah derasnya arus zaman yang terus berubah, pesantren berdiri sebagai benteng nilai dan tempat lahirnya generasi yang tangguh. Ketangguhan yang lahir dari pesantren bukan hanya tentang kuat menghadapi kesulitan, tetapi juga tentang keteguhan dalam memegang nilai, kesabaran dalam perjuangan, dan keikhlasan dalam setiap langkah. Dari pesantren, lahir insan-insan yang siap menghadapi kehidupan dengan iman sebagai pondasi dan ilmu sebagai bekal. Inilah perjalanan menuju peradaban yang utuh.",
        'menu_rentetan': 'Rentetan Kegiatan PKA',
        'menu_data': 'Data',
        'menu_acara': 'Acara',
        'menu_serba': 'Serba-Serbi',
        'redaksi': 'Tim Redaksi',
        'menu_beranda': 'Beranda',
        'menu_keluar': 'Keluar',
        'menu_ApelTahunan': 'Apel Tahunan',
        'menu_KuliahUmum': 'Kuliah Umum',
        'menu_LatihanLKBB': 'Latihan LKBB',
        'menu_POD': 'PORSENI',
        'menu_LatihanOhpondokku': "Latihan Oh Pondokku",
        'menu_LombaCCA': 'Lomba Cerdas Cermat',
        'menu_HadrahAngkatan': 'Hadrah Antar Angkatan',
        'menu_LombaLKBB': 'Lomba LKBB',
        'menu_SingleSong': 'Single Song',
        'menu_LiveMusic': 'Live Music',
        'menu_ARN': 'Aneka Ria Nusantara',
        'menu_DA': 'Drama Arena',
        'menu_PG': 'Panggung Gembira',
        'menu_PembagianHadiah': 'Pembagian Hadiah',
        'narasiup_rentetan': 'Pekan Perkenalan Khutbatu-l-’Arsy merupakan kegiatan tahunan di awal tahun ajaran yang bertujuan menyambut santriwati baru, menumbuhkan semangat kebersamaan, serta mengenalkan nilai-nilai pondok melalui berbagai kegiatan yang aktif dan edukatif.',
        'narasi_rentetan': 'Rangkaian kegiatan dalam Pekan Perkenalan Khutbatu-l-’Arsy merupakan tradisi Pondok Modern Darussalam Gontor yang diisi dengan berbagai acara dan perlombaan untuk meningkatkan kreativitas dan kemampuan para santriwati.',
        'narasiup_data': 'Data kegiatan PKA menyajikan informasi terstruktur mengenai jumlah peserta, serta data panitia dan guru yang terlibat dalam pelaksanaan kegiatan secara jelas dan ringkas.',
        'narasiup_acara': 'Kegiatan apel dan upacara dalam PKA berperan penting dalam membentuk kedisiplinan, menanamkan nilai-nilai pondok, serta dimeriahkan dengan penampilan santriwati dan guru yang menumbuhkan kreativitas, kepercayaan diri, dan kebersamaan.',
        'narasiup_serba': 'Halaman ini merupakan ruang dokumentasi yang menampilkan berbagai elemen visual dan kreatif sebagai arsip terstruktur yang menunjukkan konsep, identitas, dan perkembangan desain website.',
        'narasi_ApelTahunan': 'Apel Tahunan adalah upacara tahunan yang resmi dan wajib diikuti oleh seluruh keluarga besar Pondok Modern. Acara ini berisi upacara bendera, inspeksi, amanat, parade, serta penampilan-penampilan yang menunjukkan bakat santriwati.',
        'narasi_KuliahUmum': 'Kuliah Umum dilaksanakan setelah apel tahunan dan berisi penjelasan mengenai aspek akademik dan nilai pesantren oleh pimpinan.',
        'narasi_LatihanLKBB': 'Latihan ketangkasan baris-berbaris antarkonsulat adalah agenda rutin yang bertujuan melatih disiplin dan kerjasama antar peserta.',
        'narasi_POD': 'PORSENI adalah Pekan Olahraga dan Seni yang menjadi pembuka rangkaian, mengakomodasi kompetisi olahraga dan seni dengan semangat sportivitas.',
        'narasi_LatihanOhpondokku': "Latihan menyanyi Hymne 'Oh Pondokku' untuk menumbuhkan rasa cinta dan kebanggaan terhadap pondok.",
        'narasi_LombaCCA': 'LCC (Lomba Cerdas Cermat) menguji kemampuan intelektual dan kerja tim antar rayon.',
        'narasi_HadrahAngkatan': 'Hadrah antar angkatan menampilkan lantunan shalawat sebagai ekspresi keagamaan dan seni.',
        'narasi_LombaLKBB': 'Lomba ketangkasan baris-berbaris melambangkan ketangkasan dan kebersamaan peserta.',
        'narasi_SingleSong': 'Single Song adalah lomba tarik suara antar peserta.',
        'narasi_LiveMusic': 'Live Music memberi ruang bagi peserta menampilkan bakat musik dan vokal.',
        'narasi_ARN': 'Aneka Ria Nusantara menampilkan tarian dan masakan tradisional dari berbagai daerah.',
        'narasi_DA': 'Drama Arena adalah pagelaran seni yang melibatkan peserta terpilih.',
        'narasi_PG': 'Panggung Gembira adalah acara puncak yang meriah dan terorganisir.',
        'narasi_PembagianHadiah': 'Pembagian hadiah sebagai bentuk apresiasi terhadap prestasi peserta.'
    },
    en: {
        'judul_1': 'ORIENTATION WEEK',
        'judul_2': "KHUTBATU-L-'ARSY",
        'slogan': '"Pesantrens produce resilient students, creating a complete civilization."',
        'narasi_pembuka': 'Amidst the rushing currents of changing times, pesantrens stand as fortresses of values and the birthplace of a resilient generation.',
        'menu_rentetan': 'Sequence of Events',
        'menu_data': 'Data',
        'menu_acara': 'Events',
        'menu_serba': 'Miscellaneous',
        'redaksi': 'Editorial Team',
        'menu_beranda': 'Home',
        'menu_keluar': 'Logout',
        'menu_ApelTahunan': 'Annual Assembly',
        'menu_KuliahUmum': 'General Lecture',
        'menu_LatihanLKBB': 'Marching Skills Training',
        'menu_POD': 'Sports and Arts Week',
        'menu_LatihanOhpondokku': "Oh Pondokku Singing Practice",
        'menu_LombaCCA': 'Quiz Competition',
        'menu_HadrahAngkatan': 'Hadrah Between Generations',
        'menu_LombaLKBB': 'Marching Competition',
        'menu_SingleSong': 'Single Song',
        'menu_LiveMusic': 'Live Music',
        'menu_ARN': 'Aneka Ria Nusantara',
        'menu_DA': 'Drama Arena',
        'menu_PG': 'Panggung Gembira',
        'menu_PembagianHadiah': 'Prize Distribution',
        'narasiup_rentetan': 'Khutbatu-l-’Arsy Orientation Week is an annual program held at the beginning of the academic year to welcome new students.',
        'narasiup_data': 'PKA activity data presents structured information on participants and organizers.',
        'narasiup_acara': 'Assembly and ceremony activities in PKA build discipline and togetherness.',
        'narasiup_serba': 'This page documents visual and creative elements as a structured archive.',
        'narasi_ApelTahunan': 'The Annual Assembly is an official ceremony including flag ceremony, inspection and performances.',
        'narasi_KuliahUmum': 'The General Lecture is a speech about pondok values and systems delivered by leadership.',
        'narasi_LatihanLKBB': 'Marching training strengthens discipline and team cooperation.',
        'narasi_POD': 'PORSENI is a Sports and Arts Week featuring competitions in sports and arts.',
        'narasi_LatihanOhpondokku': "Oh Pondokku hymn practice prepares students for official events.",
        'narasi_LombaCCA': 'Quiz Competition tests knowledge and teamwork among rayons.',
        'narasi_HadrahAngkatan': 'Hadrah performances are religious musical expressions by classes.',
        'narasi_LombaLKBB': 'Marching competition showcases agility and coordination.',
        'narasi_SingleSong': 'Single Song competition highlights vocal talent.',
        'narasi_LiveMusic': 'Live music showcases bands and singers.',
        'narasi_ARN': 'Aneka Ria Nusantara showcases regional dances and cooking.',
        'narasi_DA': 'Drama Arena is a staged theatrical performance.',
        'narasi_PG': 'Panggung Gembira is the grand festive stage show.',
        'narasi_PembagianHadiah': 'Prize distribution honors winners and participants.'
    },
    ar: {
        'judul_1': 'أسبوع التعارف',
        'judul_2': "خطبة العرش",
        'slogan': '"جونتور تلتزم بغرس القيم الإسلامية"',
        'narasi_pembuka': 'في خِضَمِّ أَمْوَاجِ العَصْرِ الْمُتَغَيِّرَةِ، تَقِفُ المَعَاهِدُ كَحِصْنٍ لِلْقِيَمِ وَمَهْدٍ لِجِيْلٍ صَامِدٍ.',
        'menu_acara': 'البرامج',
        'menu_beranda': 'الرئيسية',
        'menu_rentetan': 'جدول البرامج',
        'menu_data': 'البيانات',
        'menu_serba': 'متنوعات',
        'menu_keluar': 'خروج',
        'menu_ApelTahunan': 'اللقاء السنوي',
        'menu_KuliahUmum': 'المحاضرة العامة',
        'menu_LatihanLKBB': 'تدريب مهارات المشي',
        'menu_POD': 'أسبوع الرياضة والفنون',
        'menu_LatihanOhpondokku': "تدريب غناء نشيد 'أوه بوندك'",
        'menu_LombaCCA': 'مسابقة الأسئلة',
        'menu_HadrahAngkatan': 'الحدرة بين الأجيال',
        'menu_LombaLKBB': 'مسابقة المشي',
        'menu_SingleSong': 'أغنية منفردة',
        'menu_LiveMusic': 'الموسيقى الحية',
        'menu_ARN': 'أنيكا ريا نوسانتارا',
        'menu_DA': 'دراما أرينا',
        'menu_PG': 'المسرح السعيد',
        'menu_PembagianHadiah': 'توزيع الجوائز',
        'narasiup_rentetan': 'برنامج أسبوع التعارف هو فعالية سنوية تُقام لاستقبال الطالبات الجدد وتعريفهن بقيم المعهد.',
        'narasiup_data': 'تقدم بيانات PKA معلومات منظمة عن المشاركات واللجان.',
        'narasiup_acara': 'تساهم أنشطة الطابور والاحتفال في تعزيز الانضباط والتعاون.',
        'narasiup_serba': 'توثق هذه الصفحة العناصر البصرية والإبداعية كأرشيف منظّم.',
        'narasi_ApelTahunan': 'اللقاء السنوي يتضمن حفل العلم والتفتيش والعروض الفنيّة.',
        'narasi_KuliahUmum': 'المحاضرة العامة تتناول قيم ونظم المعهد يقدمها القيادة.',
        'narasi_LatihanLKBB': 'تدريب المشي يعزز الانضباط والعمل الجماعي.',
        'narasi_POD': 'PORSENI هو أسبوع الرياضة والفنون الذي يتضمن مسابقات الرياضة والفنون.',
        'narasi_LatihanOhpondokku': 'تدريب نشيد Oh Pondokku لتحضير الطالبات للفعاليات الرسمية.',
        'narasi_LombaCCA': 'مسابقة الأسئلة تختبر المعرفة والعمل الجماعي بين الرايونات.',
        'narasi_HadrahAngkatan': 'العروض الحنينية تعبر عن الروح الدينية والفنية.',
        'narasi_LombaLKBB': 'مسابقة المشي تظهر الرشاقة والتنسيق.',
        'narasi_SingleSong': 'مسابقة الأغنية الفردية تظهر المواهب الصوتية.',
        'narasi_LiveMusic': 'الموسيقى الحية تعرض الفرق والمغنيات.',
        'narasi_ARN': 'أنيكا ريا نوسانتارا تعرض الرقص والطهي الإقليمي.',
        'narasi_DA': 'دراما أرينا هو عرض مسرحي مقتدس مؤدًى من الطالبات.',
        'narasi_PG': 'المسرح السعيد هو العرض الختامي والمبهج.',
        'narasi_PembagianHadiah': 'توزيع الجوائز لتكريم الفائزين والمشاركين.'
    }
};