const kamus = {
    'id' : {
        'judul_1' : 'PEKAN PERKENALAN',
        'judul_2' : "KHUTBATU-L-'ARSY",
        'slogan' : '"Pesantren melahirkan santri yang tangguh, menciptakan peradaban yang utuh."',
        'narasi_pembuka' : "Ditengah derasnya arus zaman yang terus berubah, pesantren berdiri sebagai benteng nilai dan tempat lahirnya generasi yang Tangguh, ketangguhan yang lahir dari pesantren bukan hanya tentang kuat menghadapi kesulitan, tetapi juga tentang keteguhan dalam memegang nilai, kesabaran dalam perjuangan, dan keikhlasan dalam setiap Langkah. Dari pesantren, lahir insan-insan yang siap menghadapi kehidupan dengan iman sebagai pondasi dan ilmu sebagai bekal sebuah peradaban yang tidak mudah runtuh oleh waktu, tidak goyah oleh tantangan, dan tetap berdiri kokoh dalam setiap perubahan, karena sejatinya, peradaban yang utuh dibangun oleh manusia yang utuh. Inilah perjalanan menuju peradaban yang utuh. Sebuah perjalanan Panjang yang dimulai dari diri, dibangun Bersama, dan diwariskan untuk masa depan.",
        'menu_rentetan' : 'Rentetan Kegiatan PKA',
        'menu_data' : 'Data',
        'menu_acara' : 'Acara',
        'menu_serba' : 'Serba-Serbi',
        'redaksi' : 'Tim Redaksi',
        'menu_beranda' : 'Beranda',
        'menu_keluar' : 'Keluar',
        'menu_ApelTahunan' : 'Apel Tahunan',
        'menu_KuliahUmum' : 'Kuliah Umum',
        'menu_LatihanLKBB' : 'Latihan LKBB',
        'menu_POD' : 'PORSENI',
        'menu_LatihanOhpondokku' : "Latihan Oh Pondokku",
        'menu_LombaCCA' : 'Lomba Cerdas Cermat',
        'menu_HadrahAngkatan' : 'Hadrah Antar Angkatan',
        'menu_LombaLKBB' : 'Lomba LKBB',
        'menu_SingleSong' : 'Single Song',
        'menu_LiveMusic' : 'Live Music',
        'menu_ARN' : 'Aneka Ria Nusantara',
        'menu_DA' : 'Drama Arena',
        'menu_PG' : 'Panggung Gembira',
        'menu_PembagianHadiah' : 'Pembagian Hadiah',
        'narasiup_rentetan' :   'Pekan Perkenalan Khutbatu-l-’Arsy merupakan kegiatan tahunan di awal tahun ajaran yang bertujuan menyambut santriwati baru, menumbuhkan semangat kebersamaan, serta mengenalkan nilai-nilai pondok melalui berbagai kegiatan yang aktif dan edukatif.',
        'narasi_rentetan' : 'Rangkaian kegiatan dalam Pekan Perkenalan Khutbatu-l-’Arsy merupakan sunnah Pondok Modern Darussalam Gontor yang diisi dengan berbagai acara dan perlombaan untuk meningkatkan kreativitas dan kemampuan para santriwati. Setiap kegiatan menjadi wadah pengembangan potensi, melatih keterampilan, serta menumbuhkan semangat berkompetisi secara sehat, sehingga turut memeriahkan dan menghidupkan suasana PKA dengan penuh antusiasme dan kebersamaan.',
        'narasiup_data' : 'Data kegiatan PKA menyajikan informasi terstruktur mengenai jumlah peserta, serta data panitia dan guru yang terlibat dalam pelaksanaan kegiatan secara jelas dan ringkas.',
        'narasiup_acara' :'Kegiatan apel dan upacara dalam PKA berperan penting dalam membentuk kedisiplinan, menanamkan nilai-nilai pondok, serta dimeriahkan dengan penampilan santriwati dan guru yang menumbuhkan kreativitas, kepercayaan diri, dan kebersamaan.',
        'narasiup_serba' :'Halaman ini merupakan ruang dokumentasi yang menampilkan berbagai elemen visual dan kreatif seperti shape, desain grafis, dan komponen pendukung sebagai arsip terstruktur yang menunjukkan konsep, identitas, dan perkembangan desain website.',
        'narasi_ApelTahunan' :'Apel Tahunan adalah upacara tahunan yang resmi dan wajib diikuti oleh seluruh keluarga besar Pondok Modern. Acara ini tidak hanya meliputi upacara bendera, di dalamnya terdapat nilai-nilai positif yang dapat dipetik dan dirasakan. Acara ini berisi upacara bendera, inspeksi dan amanat yang disampaikan oleh Bapak Pimpinan Pondok Modern Darussalam Gontor, parade barisan guru dan santriwati, serta penampilan-penampilan yang menunjukkan bakat dan kreatifitas santriwati',
        'narasi_KuliahUmum' :'Kuliah Umum adalah acara yang dilakukan setelah melaksanakan apel tahunan. Kuliah umum merupakan pidato yang berisikan penjelasan mengenai segala aspek Pondok Modern Darussalam Gontor, nilai-nilai, sistem pembelajaran dan pendidikan, filsafat kehidupan pondok, serta penjelasan tentang Kulliyatu-l-Mu’allimat Al- Islamiyah. Pidato tersebut disampaikan secara langsung oleh Bapak Pimpinan Pondok Modern Darussalam Gontor yang bertempat di Auditorium Gontor Putri Kampus 3 dan dihadiri oleh semua guru dan santriwati.',
        'narasi_LatihanLKBB' :'Latihan ketangkasan baris-berbaris antarkonsulat merupakan salah satu agenda rutin yang selalu diadakan dalam rangkaian kegiatan Apel Tahunan. Kegiatan ini tidak hanya menjadi ajang untuk keterampilan baris-berbaris, tetapi juga menjadi sarana strategis dalam mempererat tali ukhuwah islamiyah di antara para santriwati di berbagai konsulat. Melalui latihan ini, diharapkan dapat terciptanya semangat kebersamaan yang kuat, kekompakkan, serta kemampuan bekerja sama dalam satu tim yang solid. Selain itu, latihan ini menjadi media untuk menanamkan nilai-nilai kedisiplinan, tanggung jawab dan kepemimpinan dalam diri setiap peserta. Kegiatan ini nantinya akan dilombakan pada Apel Tahunan Khutbatu-l-’Arsy dengan mengikuti rute khusus yang telah dirancang dan ditetapkan oleh panitia pelaksana. Sementara penilaian dilakukan secara objektif oleh para dewan juri dari guru-guru. Dengan dilombakannya kegiatan ini, harapannya tercipta suasana yang kompetitif namun tetap menjunjung tinggi nilai persaudaraan di antara seluruh peserta tiap konsulat.',
        'narasi_POD' :'Pekan Olahraga dan Seni (PORSENI) merupakan acara pembuka dari rangkaian kegiatan Pekan Perkenalan Khutbatu-l-’Arsy yang diselenggarakan pada hari Jum’at 19 Syawwal 1446 H bertepatan dengan 18 April 2025 M. Acara ini menjadi momen penting untuk membangkitkan semangat para santriwati agar dapat berpartisipasi secara aktif dalam seluruh program pesantren sepanjang tahun ajaran. PORSENI dirancang sebagai ajang kompetitif yang mewadahi minat dan bakat para santriwati dalam dua bidang utama, yaitu oalhraga dan seni. Berbagai perlombaan diselenggarakan dalam suasana yang kompetitif sekaligus mendidik dengan menjunjung nilai-nilai sportivitas, kejujuran dan ukhuwah. Melalui kegiatan ini, para santriwati tidak hanya dapat menyalurkan bakat dan kemampuan mereka, tetapi juga dilatih untuk tampil percaya diri, bekerja sama dalam tim. Serta mampu menunjukkan ketekunan dan rasa tanggung jawab dalam setiap pertandingan maupun penampilan seni. Sebagai bentuk penghargaan atas usaha, semangat, dan prestasi yang ditunjukkan oleh peserta, panitia mengapresiasi dengan memberikan hadiah kepada juara umum disetiap kategorinya. Kelas 4 menjadi juara umum antarangkatan, Rayon Cordova A menjadi juara umum antarrayon, dan Gedung Hijaz sebagai juara umum antargedung',
        'narasi_LatihanOhpondokku': "Latihan Menyanyi Lagu Hymne 'Oh Pondokku' merupakan langkah awal yang sangat penting dalam rangka mempersiapkan para santriwati sebelum diselenggarakannya Apel Tahunan maupun berbagai acara resmi lainnya di lingkungan pesantren. Kegiatan ini bukan sekadar sesi latihan vokal biasa, melainkan sebuah proses pembelajaran yang bertujuan untuk membentuk rasa cinta dan kebanggaan terhadap pondok pesantren sebagai tempat menuntut ilmu, membina akhlak, dan membangun karakter. Melalui latihan menyanyi hymne ini, para santriwati diajak untuk mengenal lebih dalam nilainilai dasar yang menjadi landasan kehidupan pondok modern. Oleh karena itu, pelatihan ini memiliki nilai simbolik yang kuat dalam menanamkan jiwa kepondokmodernan kepada setiap santriwati, khususnya para santriwati baru yang sedang dalam tahap awal penyesuaian diri di lingkungan baru. Dengan latihan yang terstruktur dan penuh makna ini, diharapkan para santriwati dapat menyanyikannya dengan penuh penghayatan dan semangat saat tampil dalam momen-momen resmi pesantren.",
        'narasi_LombaCCA' :'Lomba Cerdas Cermat (LCC) merupakan salah satu kegiatan kompetitif yang melibatkan santriwati dari setiap rayon, masing-masing mengirimkan tim beranggotakan tiga orang. Kegiatan ini dirancang sebagai ajang untuk mengasah kemampuan intelektual para santriwati serta menggali potensi mereka dalam bidang ilmu pengetahuan umum maupun keagamaan. Melalui perlombaan ini, para peserta tidak hanya diuji dari segi kecepatan dan ketepatan dalam menjawab pertanyaan, tetapi juga dituntut untuk bekerja sama dalam tim secara kompak dan strategis. Puncak acara Lomba Cerdas Cermat ini diselenggarakan pada hari Jum’at, 27 Syawwal 1446 H, yang bertepatan dengan tanggal 26 April 2025 M. Acara berlangsung di auditorium Gontor Putri Kampus 3 dengan penuh semangat dan antusiasme. Untuk memberikan penghargaan atas usaha yang telah dilakukan, panitia memberikan apresiasi kepada tim terbaik yang berhasil meraih juara pada perlombaan ini. Adapun juara Lomba Cerdas Cermat tahun ini berhasil diraih oleh Rayon Thoif B. Semoga kegiatan ini menjadi pemicu semangat belajar bagi seluruh santriwati dan memperkuat atmosfer ilmiah di lingkungan pesantren.',
        'narasi_HadrahAngkatan' :'Pada hari Jum’at tanggal 2 Mei 2025 telah diselenggarakan lomba Hadrah Antar Angkatan dengan tujuan untuk mensyiarkan agama Allah. Lantunan shalawat yang dikumandangkan dengan penuh semangat dan kekompakan menjadi bukti nyata kecintaan para santriwati terhadap Rasulullah صلى الله عليه وسلم. Iringan alat hadrah yang dimainkan dengan harmonis turut menambah semarak suasana, menjadikan momen ini bukan sekadar perlombaan, melainkan bagian dari pendidikan karakter dan dakwah bil-fann (dakwah melalui seni). Kegiatan ini menjadi ajang untuk menyalurkan kreativitas para santriwati, serta mendorong tumbuhnya pribadi santriwati yang sitti-l-kull (perempuan yang serba bisa). Selain itu, lomba ini juga mempererat ukhuwah Islamiyah di antara para peserta, yang menjadi fondasi penting bagi kekompakan setiap angkatan. Dalam perlombaan ini, angkatan Kelas Tiga berhasil meraih juara pertama, sedangkan angkatan Kelas Tiga Intensif memperoleh juara kedua.',
        'narasi_LombaLKBB' :'Lomba ketangkasan baris berbaris melambangkan Gerak-gerik santriwati yang cepat dan tanggap dan juga melambangkan ketangkasan serta keaktifan. Lomba ini diadakan pada hari Senin, 21 April 2025 yang di menangkan oleh rayon Lahore B sebagai pemenang pertama dan rayon Cordova A sebagai juara kedua. Kegiatan ini memupuk nilai-nilai kebersamaan antar anggota. Peluh keringat yang bercucuran memaknai pengorbanan para mujahidah fi sabilillah dalam menuntut ilmu untuk meninggikan agama Allah.',
        'narasi_SingleSong' :'Untuk mencetak santriwati yang multitalenta, gontor dalam rentetan Khutbatu-l-’Arsy nya mengadakan lomba Single Song. Acara ini memupuk ide kretivitas santriwati dalam seni tarik suara. Dengan melalui beberapa babak penyisihan tepat pada hari Sabtu, 26 April 2025 perlombaan ini dimenangkan oleh Yumna Dhia sebagai juara yang pertama dan Naira Oktariza sebagai juara kedua.',
        'narasi_LiveMusic' :'Musik merupakan salah satu seni yang tak akan lekang oleh waktu dan tak akan lapuk dimakan oleh zaman. Gontor dalam rentetan khutbatu-l-’arsy nya mengadakan perlombaan ini yang bertujuan untuk memberi ruang pada santriwatinya agar mengekspresikan minat dan bakatnya dalam seni Tarik suara sehingga dapat memupuk generasi yangmultitalenta dalam segala aspek kehidupan, diadakan pada Sabtu, 26 April 2025 dimenangkan oleh Khalila Maziyyaturrohmah sebagai juara pertama dan Asy Syifa Aulia Sebagai juara kedua.',
        'narasi_ARN' :'Aneka Ria Nusantara merupakan salah satu agenda tahunan yang menjadi bagian tak terpisahkan dari rangkaian kegiatan Pekan Perkenalan. Kegiatan ini mengemban misi untuk mempererat ukhuwah Islamiyah antar konsulat serta menumbuhkan rasa cinta dan kebanggaan terhadap daerah asal masingmasing santri. Kegiatan ini terbagi ke dalam dua cabang perlombaan, yaitu Tari Nusantara dan Memasak. Seluruh rangkaian acara diselenggarakan diAuditorium pada hari Kamis, 24 April 2025. dan Untuk juara pertama dari Tari Nusantara adalah Jawa Tengah dan juara pertama untuk memasak adalah Sumatra.',
        'narasi_DA' :'Salah satu rangkaian istimewa dalam Pekan Perkenalan Khutbatu-l-’Arsy adalah pagelaran seni Drama Arena yang dipersembahkan oleh siswi kelas 5 KMI Pondok Modern Darussalam Gontor Putri Kampus 3. Acara yang akan diselenggarakan pada 13 Mei 2026 ini mengusung motto “Hidup berlandaskan nilai, menjadi jejak dalam keteladanan.” Melalui pagelaran ini, diharapkan terbangun kerja sama tim yang solid sekaligus menghadirkan apresiasi seni budaya yang berkelas, tanpa mengesampingkan nilai-nilai Islam sebagai landasan utama dalam setiap unsur pendidikannya.',
        'narasi_PG' :'Pangung Gembira siswi akhir KMI merupakan acara puncak pekan perkenalan khutbatu-l-‘arsy pondok modern Darussalam gontoe putri kampus 3, kegiatan ini ditata secara apik dan menarik, serta dikelola secara total, profesioanal, dan berkaliber tinggi. Melalui pagelaran seni dan budaya yang kreatif serta spektakuler, tanpa meninggalkan nilai-nilai islam dan unsur Pendidikan yang menjadi ruh utama kehidupan pondok. Acara ini akan diselenggarakan pada 15 Mei 2026. IMPERVIOUS GENERATION beranggotakan 464 siswi telah mengikrarakan mottonya yaitu, “pesantren berjuang mendidik umat. Santri berkarya menegakkan tonggak peradaban.” Diharapkan generasi ini menjadi alumni yang khusnul khotimah dan siap untuk berkiprah dimedan jihad selanjutnya.',
        'narasi_PembagianHadiah' :'Pembagian hadiah diadakan pada hari Ahad, 4 Mei 2025. Kegiatan ini merupakan bentuk apresiasi atas partisipasi, semangat, dan prestasi para santriwati dalam berbagai perlombaan yang telah dilaksanakan. Juara umum dari masing-masing divisi adalah Kelas 3 menjadi juara umum antarangkatan, Jawa Tengah menjadi juara umum antarkonsulat dan Gedung Hijaz menjadi juara umum antargedung.'
},
    'en' : {
        'judul_1': 'ORIENTATION WEEK',
        'judul_2': "KHUTBATU-L-'ARSY",
        'slogan': '"Pesantrens produce resilient students, creating a complete civilization."',
        'narasi_pembuka': 'Amidst the rushing currents of changing times, pesantrens stand as fortresses of values and the birthplace of a resilient generation.',
        'menu_rentetan': 'Sequence of Events',
        'menu_data': 'Data',
        'menu_acara': 'Events',
        'menu_serba': 'Miscellaneous',
        'redaksi': 'Editorial Team',
        'menu_beranda': 'Home',
        'menu_keluar': 'Logout',
        'menu_ApelTahunan': 'Annual Assembly',
        'menu_KuliahUmum': 'General Lecture',
        'menu_LatihanLKBB': 'Marching Skills Training',
        'menu_POD': 'Sports and Arts Week',
        'menu_LatihanOhpondokku': "Oh Pondokku Singing Practice",
        'menu_LombaCCA': 'Quiz Competition',
        'menu_HadrahAngkatan': 'Hadrah Between Generations',
        'menu_LombaLKBB': 'Marching Competition',
        'menu_SingleSong': 'Single Song',
        'menu_LiveMusic': 'Live Music',
        'menu_ARN': 'Aneka Ria Nusantara',
        'menu_DA': 'Drama Arena',
        'menu_PG': 'Panggung Gembira',
        'menu_PembagianHadiah': 'Prize Distribution',
        'narasiup_rentetan': 'Khutbatu-l-’Arsy Orientation Week is an annual program held at the beginning of the academic year to welcome new students.',
        'narasiup_data': 'PKA activity data presents structured information on participants and organizers.',
        'narasiup_acara': 'Assembly and ceremony activities in PKA build discipline and togetherness.',
        'narasiup_serba': 'This page documents visual and creative elements as a structured archive.',
        'narasi_ApelTahunan': 'The Annual Assembly is an official ceremony including flag ceremony, inspection and performances.',
        'narasi_KuliahUmum': 'The General Lecture is a speech about pondok values and systems delivered by leadership.',
        'narasi_LatihanLKBB': 'Marching training strengthens discipline and team cooperation.',
        'narasi_POD': 'PORSENI is a Sports and Arts Week featuring competitions in sports and arts.',
        'narasi_LatihanOhpondokku': "Oh Pondokku hymn practice prepares students for official events.",
        'narasi_LombaCCA': 'Quiz Competition tests knowledge and teamwork among rayons.',
        'narasi_HadrahAngkatan': 'Hadrah performances are religious musical expressions by classes.',
        'narasi_LombaLKBB': 'Marching competition showcases agility and coordination.',
        'narasi_SingleSong': 'Single Song competition highlights vocal talent.',
        'narasi_LiveMusic': 'Live music showcases bands and singers.',
        'narasi_ARN': 'Aneka Ria Nusantara showcases regional dances and cooking.',
        'narasi_DA': 'Drama Arena is a staged theatrical performance.',
        'narasi_PG': 'Panggung Gembira is the grand festive stage show.',
        'narasi_PembagianHadiah': 'Prize distribution honors winners and participants.'
    },
    ar: {
        'judul_1': 'أسبوع التعارف',
        'judul_2': "خطبة العرش",
        'slogan': '"جونتور تلتزم بغرس القيم الإسلامية"',
        'narasi_pembuka': 'في خِضَمِّ أَمْوَاجِ العَصْرِ الْمُتَغَيِّرَةِ، تَقِفُ المَعَاهِدُ كَحِصْنٍ لِلْقِيَمِ وَمَهْدٍ لِجِيْلٍ صَامِدٍ.',
        'menu_acara': 'البرامج',
        'menu_beranda': 'الرئيسية',
        'menu_rentetan': 'جدول البرامج',
        'menu_data': 'البيانات',
        'menu_serba': 'متنوعات',
        'menu_keluar': 'خروج',
        'menu_ApelTahunan': 'اللقاء السنوي',
        'menu_KuliahUmum': 'المحاضرة العامة',
        'menu_LatihanLKBB': 'تدريب مهارات المشي',
        'menu_POD': 'أسبوع الرياضة والفنون',
        'menu_LatihanOhpondokku': "تدريب غناء نشيد 'أوه بوندك'",
        'menu_LombaCCA': 'مسابقة الأسئلة',
        'menu_HadrahAngkatan': 'الحدرة بين الأجيال',
        'menu_LombaLKBB': 'مسابقة المشي',
        'menu_SingleSong': 'أغنية منفردة',
        'menu_LiveMusic': 'الموسيقى الحية',
        'menu_ARN': 'أنيكا ريا نوسانتارا',
        'menu_DA': 'دراما أرينا',
        'menu_PG': 'المسرح السعيد',
        'menu_PembagianHadiah': 'توزيع الجوائز',
        'narasiup_rentetan': 'برنامج أسبوع التعارف هو فعالية سنوية تُقام لاستقبال الطالبات الجدد وتعريفهن بقيم المعهد.',
        'narasiup_data': 'تقدم بيانات PKA معلومات منظمة عن المشاركات واللجان.',
        'narasiup_acara': 'تساهم أنشطة الطابور والاحتفال في تعزيز الانضباط والتعاون.',
        'narasiup_serba': 'توثق هذه الصفحة العناصر البصرية والإبداعية كأرشيف منظّم.',
        'narasi_ApelTahunan': 'اللقاء السنوي يتضمن حفل العلم والتفتيش والعروض الفنيّة.',
        'narasi_KuliahUmum': 'المحاضرة العامة تتناول قيم ونظم المعهد يقدمها القيادة.',
        'narasi_LatihanLKBB': 'تدريب المشي يعزز الانضباط والعمل الجماعي.',
        'narasi_POD': 'PORSENI هو أسبوع الرياضة والفنون الذي يتضمن مسابقات الرياضة والفنون.',
        'narasi_LatihanOhpondokku': 'تدريب نشيد Oh Pondokku لتحضير الطالبات للفعاليات الرسمية.',
        'narasi_LombaCCA': 'مسابقة الأسئلة تختبر المعرفة والعمل الجماعي بين الرايونات.',
        'narasi_HadrahAngkatan': 'العروض الحنينية تعبر عن الروح الدينية والفنية.',
        'narasi_LombaLKBB': 'مسابقة المشي تظهر الرشاقة والتنسيق.',
        'narasi_SingleSong': 'مسابقة الأغنية الفردية تظهر المواهب الصوتية.',
        'narasi_LiveMusic': 'الموسيقى الحية تعرض الفرق والمغنيات.',
        'narasi_ARN': 'أنيكا ريا نوسانتارا تعرض الرقص والطهي الإقليمي.',
        'narasi_DA': 'دراما أرينا هو عرض مسرحي مقتدس مؤدًى من الطالبات.',
        'narasi_PG': 'المسرح السعيد هو العرض الختامي والمبهج.',
        'narasi_PembagianHadiah': 'توزيع الجوائز لتكريم الفائزين والمشاركين.'
    }
};